// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE34zUYen0xezRUTPpYWkNQ3W_PKYBOnk',
    appId: '1:648121103499:web:42b55d818cfc7429a0908e',
    messagingSenderId: '648121103499',
    projectId: 'bksproject-29e05',
    authDomain: 'bksproject-29e05.firebaseapp.com',
    storageBucket: 'bksproject-29e05.appspot.com',
    measurementId: 'G-L2FZM736NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeq_I-hRKgYgtfF_VxRLzTGZbeUyMEyKU',
    appId: '1:648121103499:android:ad53b1df8b95d08aa0908e',
    messagingSenderId: '648121103499',
    projectId: 'bksproject-29e05',
    storageBucket: 'bksproject-29e05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI4Gd1pD-IAUrzK-IBjqQZmlgaURNT7G8',
    appId: '1:648121103499:ios:5dec0d9dfd10c712a0908e',
    messagingSenderId: '648121103499',
    projectId: 'bksproject-29e05',
    storageBucket: 'bksproject-29e05.appspot.com',
    iosClientId: '648121103499-af9aqli3eaakgugfabbudjvv0m4cmecn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bksproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI4Gd1pD-IAUrzK-IBjqQZmlgaURNT7G8',
    appId: '1:648121103499:ios:f4a38645a0eee68ca0908e',
    messagingSenderId: '648121103499',
    projectId: 'bksproject-29e05',
    storageBucket: 'bksproject-29e05.appspot.com',
    iosClientId: '648121103499-j2814qh6g08nactfdbg29k8v442k1cfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bksproject.RunnerTests',
  );
}
